### ISSUE TITLE
Record id mismatch

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#210]
```
Batch #20: PUT /buckets/build-hub/collections/releases/records/thunderbird_1-0_linux-i686-gtk22bxft_tr-tr - 400 Record id does not match existing record
Exception in callback consume.<locals>.markdone.<locals>.done(<Future finis...rno': 107}",)>) at /home/ubuntu/buildhub/jobs/buildhub/to_kinto.py:128
handle: <Handle consume.<locals>.markdone.<locals>.done(<Future finis...rno': 107}",)>) at /home/ubuntu/buildhub/jobs/buildhub/to_kinto.py:128>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/ubuntu/buildhub/jobs/buildhub/to_kinto.py", line 130, in done
    results = future.result()  # will raise exception if failed.
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/buildhub/jobs/buildhub/to_kinto.py", line 95, in publish_records
    raise ValueError("\n".join(error_msgs))
ValueError: Invalid record: {'message': 'Record id does not match existing record', 'code': 400, 'details': [{'location': 'body', 'description': 'Record id does not match existing record', 'name': 'id'}], 'error': 'Invalid parameters', 'errno': 107}
```

**Comment by Natim** [comment]
This happens when you try to set and ID in the body that is different from the one in the URL

**Comment by leplatrem** [comment]
I truely wonder how this can happen, because the code in `to_kinto` is just:
```py
with client.batch() as batch:
        for record in records:
            if "id" in record["data"]:
                batch.update_record(**record)
            else:
                batch.create_record(**record)
```

The kinto-http lib is in charge of figuring out the url...

**Comment by leplatrem** [comment]
Not occuring anymore with the new approach
