### ISSUE TITLE
Crash with Fennec wince

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#224]
```
https://archive.mozilla.org/pub/mobile/releases/wince/1.0a3/fennec-1.0a3.en-US.wince-arm.zip
Traceback (most recent call last):
  File "/home/ubuntu/buildhub/jobs/buildhub/inventory_to_records.py", line 335, in csv_to_records
    record = record_from_url(url)
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 314, in record_from_url
    "os": normalized_platform(platform),
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 99, in normalized_platform
    raise ValueError("Unknown plaform {}".format(platform))
ValueError: Unknown plaform 1.0a3
```

**Comment by leplatrem** [comment]
```
https://archive.mozilla.org/pub/mobile/releases/winmo/1.0a3/fennec-1.0a3.en-US.wince-arm.zip
Traceback (most recent call last):
  File "/home/ubuntu/buildhub/jobs/buildhub/inventory_to_records.py", line 335, in csv_to_records
    record = record_from_url(url)
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 314, in record_from_url
    "os": normalized_platform(platform),
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 99, in normalized_platform
    raise ValueError("Unknown plaform {}".format(platform))
ValueError: Unknown plaform 1.0a3
```
