### ISSUE TITLE
Easy 504 Gateway Time-out

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#240]
```
Waiting for records in the queue.                                                                                                                                                                                                      
https://buildhub.stage.mozaws.net:443 "POST /v1/batch HTTP/1.1" 504 176  
Starting new HTTPS connection (1): buildhub.stage.mozaws.net                                                                                                                                                                           
Waiting for records in the queue.                                        
https://buildhub.stage.mozaws.net:443 "POST /v1/batch HTTP/1.1" 504 176                                                                                                                                                                
Starting new HTTPS connection (1): buildhub.stage.mozaws.net
https://buildhub.stage.mozaws.net:443 "POST /v1/batch HTTP/1.1" 504 176
Update record with id 'firefox_nightly_2017-08-18-10-02-26_57-0a1_win32_xh' in collection 'releases' in bucket 'buildhub'
Update record with id 'firefox_nightly_2017-08-18-10-02-26_57-0a1_win64_xh' in collection 'releases' in bucket 'buildhub'
Update record with id 'firefox_nightly_2017-08-18-10-02-26_57-0a1_linux-i686_af' in collection 'releases' in bucket 'buildhub'
Update record with id 'firefox_nightly_2017-08-18-10-02-26_57-0a1_linux-i686_an' in collection 'releases' in bucket 'buildhub'
Exception in callback consume.<locals>.markdone.<locals>.done(<Future finis.../html>\r\n',)>) at /home/ubuntu/buildhub/jobs/buildhub/to_kinto.py:127
handle: <Handle consume.<locals>.markdone.<locals>.done(<Future finis.../html>\r\n',)>) at /home/ubuntu/buildhub/jobs/buildhub/to_kinto.py:127>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/home/ubuntu/buildhub/jobs/buildhub/to_kinto.py", line 129, in done
    results = future.result()  # will raise exception if failed.
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/buildhub/jobs/buildhub/to_kinto.py", line 86, in publish_records
    batch.create_record(**record)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/ubuntu/venvs/buildhub/lib/python3.6/site-packages/kinto_http/__init__.py", line 105, in batch
    batch_session.send()
  File "/home/ubuntu/venvs/buildhub/lib/python3.6/site-packages/kinto_http/batch.py", line 59, in send
    resp, headers = self.session.request(**kwargs)
  File "/home/ubuntu/venvs/buildhub/lib/python3.6/site-packages/kinto_http/session.py", line 107, in request
    raise exception
kinto_http.exceptions.KintoException: POST /v1/batch - 504 504 - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>


```

**Comment by leplatrem** [comment]
The workaround for this is to either:
- increase the timeout configured on the gateway (see [bz](https://bugzilla.mozilla.org/show_bug.cgi?id=1380695))
- use a lower batch size (see #244)
