### ISSUE TITLE
Sometimes fails to acknowledge records creation (Event loop is closed)

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#263]
Records are created when running `latest-inventory-to-kinto` but some stacktraces are shown:

```
Batch #9: PUT /buckets/build-hub/collections/releases/records/devedition_aurora_55-0b6rc1_macosx_kn - 201
                                                                                                 
Batch #9:                                                                
        Request: {"method": "PUT", "path": "/buckets/build-hub/collections/releases/records/devedition_aurora_55-0b6rc1_macosx_kn", "body": {"data": {"source": {"product": "devedition"}, "target": {"platform": "macosx", "os": "mac", "locale": "kn", "version": "55.0b6rc1", "channel": "aurora"}, "download": {"url": "https://archive.mozilla.org/pub/devedition/candidates/55.0b6-candidates/build1/mac/kn/Firefox 55.0b6.dmg", "mimetype": "application/x-apple-diskimage", "size": 66550159, "date": "2017-06-30T00:25:56Z"}, "id": "devedition_aurora_55-0b6rc1_macosx_kn"}}}
        Response: {"status": 201, "headers": {"Last-Modified": "Fri, 06 Oct 2017 14:27:53 GMT", "X-Content-Type-Options": "nosniff", "Content-Type": "application/json", "Content-Length": "474", "ETag": "\"1507300073975\"", "Access-Control-Expose-Headers": "Retry-After, Content-Length, Alert, Backoff"}, "body": {"permissions": {"write": ["account:lambda"]}, "data": {"source": {"product": "devedition"}, "id": "devedition_aurora_55-0b6rc1_macosx_kn", "target": {"os": "mac", "platform": "macosx", "locale": "kn", "channel": "aurora", "version": "55.0b6rc1"}, "download": {"url": "https://archive.mozilla.org/pub/devedition/candidates/55.0b6-candidates/build1/mac/kn/Firefox 55.0b6.dmg", "size": 66550159, "mimetype": "application/x-apple-diskimage", "date": "2017-06-30T00:25:56Z"}, "last_modified": 1507300073975}}, "path": "/v1/buckets/build-hub/collections/releases/records/devedition_aurora_55-0b6rc1_macosx_kn"}
                                                                                                 
exception calling callback for <Future at 0x7f130bc78c50 state=finished returned list>
Traceback (most recent call last):                                                               
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)                                                                               
  File "/usr/lib/python3.6/asyncio/futures.py", line 419, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)                              
  File "/usr/lib/python3.6/asyncio/base_events.py", line 620, in call_soon_threadsafe
    self._check_closed()                                                                         
  File "/usr/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')                                                   
RuntimeError: Event loop is closed                                       
Update record with id 'devedition_aurora_55-0b6rc1_macosx_sk' in collection 'releases' in bucket 'build-hub'
Update record with id 'devedition_aurora_55-0b6rc1_macosx_sl' in collection 'releases' in bucket 'build-hub'
Update record with id 'devedition_aurora_55-0b6rc1_macosx_sq' in collection 'releases' in bucket 'build-hub'
Update record with id 'devedition_aurora_55-0b6rc1_macosx_sr' in collection 'releases' in bucket 'build-hub'
Update record with id 'devedition_aurora_55-0b6rc1_macosx_sv-se' in collection 'releases' in bucket 'build-hub'
Update record with id 'devedition_aurora_55-0b6rc1_macosx_ta' in collection 'releases' in bucket 'build-hub'
Update record with id 'devedition_aurora_55-0b6rc1_macosx_te' in collection 'releases' in bucket 'build-hub'
Update record with id 'devedition_aurora_55-0b6rc1_macosx_th' in collection 'releases' in bucket 'build-hub'
Update record with id 'devedition_aurora_55-0b6rc1_macosx_tr' in collection 'releases' in bucket 'build-hub'
Update record with id 'devedition_aurora_55-0b6rc1_macosx_uk' in collection 'releases' in bucket 'build-hub'
```

**Comment by leplatrem** [comment]
Comes from:

```
Skip unchanged record firefox_nightly_2017-08-25-10-01-26_57-0a1_macosx_nn-no                    
Skip unchanged record firefox_nightly_2017-08-25-10-01-26_57-0a1_macosx_pa-in
Aborted.                                                                                         
Traceback (most recent call last):                                       
  File "/home/ubuntu/buildhub/jobs/buildhub/lambda_s3_inventory.py", line 157, in lambda_handler 
    loop.run_until_complete(asyncio.gather(*futures))                    
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete              
    return future.result()                                               
  File "/home/ubuntu/buildhub/jobs/buildhub/lambda_s3_inventory.py", line 141, in main           
    await to_kinto(loop, records_stream, kinto_client, skip_existing=True)
  File "/home/ubuntu/buildhub/jobs/buildhub/to_kinto.py", line 200, in main                      
    await produce(loop, stdin_generator, queue)                          
  File "/home/ubuntu/buildhub/jobs/buildhub/to_kinto.py", line 113, in produce                   
    async for record in records:                                         
  File "/home/ubuntu/buildhub/jobs/buildhub/inventory_to_records.py", line 337, in csv_to_records
    record = record_from_url(url)                                        
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 280, in record_from_url              
    platform = filename_parts[3]                                         
IndexError: list index out of range                                                              
Task was destroyed but it is pending!                                    
task: <Task pending coro=<async_generator_athrow()>>                                             
Traceback (most recent call last):                                       
  File "/home/ubuntu/venvs/buildhub/bin/latest-inventory-to-kinto", line 11, in <module>         
    load_entry_point('buildhub', 'console_scripts', 'latest-inventory-to-kinto')()
  File "/home/ubuntu/buildhub/jobs/buildhub/lambda_s3_inventory.py", line 157, in lambda_handler 
    loop.run_until_complete(asyncio.gather(*futures))                    
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete              
    return future.result()                                               
  File "/home/ubuntu/buildhub/jobs/buildhub/lambda_s3_inventory.py", line 141, in main           
    await to_kinto(loop, records_stream, kinto_client, skip_existing=True)
  File "/home/ubuntu/buildhub/jobs/buildhub/to_kinto.py", line 200, in main                      
    await produce(loop, stdin_generator, queue)                          
  File "/home/ubuntu/buildhub/jobs/buildhub/to_kinto.py", line 113, in produce                   
    async for record in records:                                         
  File "/home/ubuntu/buildhub/jobs/buildhub/inventory_to_records.py", line 337, in csv_to_records
    record = record_from_url(url)                                                                
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 280, in record_from_url
    platform = filename_parts[3]                                                                 
IndexError: list index out of range                                      
```

**Comment by leplatrem** [comment]
`https://archive.mozilla.org/pub/firefox/nightly/2017/08/2017-08-25-10-01-26-mozilla-central-l10n/Firefox Installer.zh-TW.exe`
