### ISSUE TITLE
ValueError: Unknown plaform v1

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#287]
```
https://archive.mozilla.org/pub/firefox/releases/56.0.1-funnelcake131/v1/win64/en-US/Firefox Setup 56.0.1.exe
Traceback (most recent call last):
  File "/home/ubuntu/buildhub/jobs/buildhub/inventory_to_records.py", line 359, in csv_to_records
    record = record_from_url(url)
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 320, in record_from_url
    'os': normalized_platform(platform),
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 109, in normalized_platform
    raise ValueError('Unknown plaform {}'.format(platform))
ValueError: Unknown plaform v1
```

**Comment by leplatrem** [comment]
```
https://archive.mozilla.org/pub/firefox/candidates/49.0.1-candidates/build3/funnelcake90/win32/en-US/Firefox Setup 49.0.1.exe
Traceback (most recent call last):
  File "/home/ubuntu/buildhub/jobs/buildhub/inventory_to_records.py", line 359, in csv_to_records
    record = record_from_url(url)
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 320, in record_from_url
    'os': normalized_platform(platform),
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 109, in normalized_platform
    raise ValueError('Unknown plaform {}'.format(platform))
ValueError: Unknown plaform funnelcake90
```

**Comment by leplatrem** [comment]
```
https://archive.mozilla.org/pub/firefox/candidates/49.0-candidates/build2/funnelcake87/win32/en-US/Firefox Setup 49.0.exe
Traceback (most recent call last):
  File "/home/ubuntu/buildhub/jobs/buildhub/inventory_to_records.py", line 359, in csv_to_records
    record = record_from_url(url)
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 320, in record_from_url
    'os': normalized_platform(platform),
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 109, in normalized_platform
    raise ValueError('Unknown plaform {}'.format(platform))
ValueError: Unknown plaform funnelcake87
```

**Comment by leplatrem** [comment]
```
https://archive.mozilla.org/pub/firefox/releases/46.0.1-funnelcake84/funnelcake84/win32/en-US/Firefox Setup 46.0.1.exe
Traceback (most recent call last):
  File "/home/ubuntu/buildhub/jobs/buildhub/inventory_to_records.py", line 359, in csv_to_records
    record = record_from_url(url)
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 320, in record_from_url
    'os': normalized_platform(platform),
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 109, in normalized_platform
    raise ValueError('Unknown plaform {}'.format(platform))
ValueError: Unknown plaform funnelcake84
```
