### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#288]
```
https://archive.mozilla.org/pub/firefox/releases/1.0rc1/Firefox Setup %281.0rc1%2C ca-AD%29.exe
Traceback (most recent call last):
  File "/home/ubuntu/buildhub/jobs/buildhub/inventory_to_records.py", line 359, in csv_to_records
    record = record_from_url(url)
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 294, in record_from_url
    platform = filename_parts[3]
IndexError: list index out of range
```

**Comment by leplatrem** [comment]
```
https://archive.mozilla.org/pub/firefox/releases/1.0rc1/Firefox Setup %281.0rc1%2C fi-FI%29.exe
Traceback (most recent call last):
  File "/home/ubuntu/buildhub/jobs/buildhub/inventory_to_records.py", line 359, in csv_to_records
    record = record_from_url(url)
  File "/home/ubuntu/buildhub/jobs/buildhub/utils.py", line 294, in record_from_url
    platform = filename_parts[3]
IndexError: list index out of range
```
