### ISSUE TITLE
latest-inventory-to-kinto failed to run

### ISSUE THREAD

**Issue by bqbn** [mozilla-services/buildhub#299]
Tried to run the cron and it failed with the following errors:

```
$ sudo docker run -it --rm -e "SERVER_URL=https://buildhub.prod.mozaws.net/v1" -e "AUTH=${USERNAME}:${PASSWORD}" -e BATCH_MAX_REQUESTS=10 mozilla/buildhub:latest latest-inventory-to-kinto
Traceback (most recent call last):
  File "/app/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/app/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/app/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (aiohttp 2.3.1 (/app/.venv/lib/python3.6/site-packages), Requirement.parse('aiohttp<=2.3.0,>=2.0.4'), {'aiobotocore'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/bin/latest-inventory-to-kinto", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/app/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/app/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/app/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/app/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/app/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/app/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (aiohttp 2.3.1 (/app/.venv/lib/python3.6/site-packages), Requirement.parse('aiohttp<=2.3.0,>=2.0.4'), {'aiobotocore'})
```

And the version of this build is the following:

```
$ sudo docker run -it --rm -e "SERVER_URL=https://buildhub.prod.mozaws.net/v1" -e "AUTH=${USERNAME}:${PASSWORD}" -e BATCH_MAX_REQUESTS=10 --entrypoint cat mozilla/buildhub:latest /app/version.json
{"name":"buildhub","commit":"717681a952a5c0fa1dd449972becdba7499e6e34","version":"","source":"https://github.com/mozilla-services/buildhub","build":"https://circleci.com/gh/mozilla-services/buildhub/20"}
```

**Comment by leplatrem** [comment]
From what I see, it looks like the container is not built using the version pinned in `requirements.txt` but with the latest ones.
