### ISSUE TITLE
A lot of `RuntimeError: Event loop is closed`

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/buildhub#361]
I'm getting a LOT of these kinds of outputs when running `latest-inventory-to-kinto`. 

```
Batch #24: PUT /buckets/build-hub/collections/releases/records/firefox_beta_53-0b4rc1_macosx_lij - 201

Batch #24:
	Request: {"method": "PUT", "path": "/buckets/build-hub/collections/releases/records/firefox_beta_53-0b4rc1_macosx_lij", "body": {"data": {"source": {"product": "firefox", "revision": "484f49860df6c257b06dac275d66651cc6f22867", "repository": "https://hg.mozilla.org/releases/mozilla-beta", "tree": "releases/mozilla-beta"}, "target": {"platform": "macosx", "os": "mac", "locale": "lij", "version": "53.0b4rc1", "channel": "beta"}, "download": {"url": "https://archive.mozilla.org/pub/firefox/candidates/53.0b4-candidates/build1/mac/lij/Firefox 53.0b4.dmg", "mimetype": "application/x-apple-diskimage", "size": 58726872, "date": "2017-03-17T13:58:09Z"}, "id": "firefox_beta_53-0b4rc1_macosx_lij", "build": {"id": "20170316212821", "date": "2017-03-16T21:28:21Z", "as": "$(CC)", "cc": "/usr/local/bin/ccache /builds/slave/m-beta-m64-0000000000000000000/build/src/clang/bin/clang -std=gnu99", "cxx": "/usr/local/bin/ccache /builds/slave/m-beta-m64-0000000000000000000/build/src/clang/bin/clang++ -std=gnu++11", "host": "x86_64-apple-darwin11.2.0", "target": "x86_64-apple-darwin11.2.0", "number": 1}}}}
	Response: {"path": "/v1/buckets/build-hub/collections/releases/records/firefox_beta_53-0b4rc1_macosx_lij", "status": 201, "headers": {"Last-Modified": "Tue, 13 Mar 2018 17:02:32 GMT", "ETag": "\"1520960552304\"", "Content-Type": "application/json", "Content-Length": "1054", "Access-Control-Expose-Headers": "Backoff, Retry-After, Alert, Content-Length", "X-Content-Type-Options": "nosniff"}, "body": {"permissions": {"write": ["basicauth:a9302d2ec674f91c44359646adaf7c51070ef4a3699ca596f22a543954e38c32"]}, "data": {"source": {"product": "firefox", "revision": "484f49860df6c257b06dac275d66651cc6f22867", "repository": "https://hg.mozilla.org/releases/mozilla-beta", "tree": "releases/mozilla-beta"}, "target": {"platform": "macosx", "os": "mac", "locale": "lij", "version": "53.0b4rc1", "channel": "beta"}, "download": {"url": "https://archive.mozilla.org/pub/firefox/candidates/53.0b4-candidates/build1/mac/lij/Firefox 53.0b4.dmg", "mimetype": "application/x-apple-diskimage", "size": 58726872, "date": "2017-03-17T13:58:09Z"}, "id": "firefox_beta_53-0b4rc1_macosx_lij", "build": {"id": "20170316212821", "date": "2017-03-16T21:28:21Z", "as": "$(CC)", "cc": "/usr/local/bin/ccache /builds/slave/m-beta-m64-0000000000000000000/build/src/clang/bin/clang -std=gnu99", "cxx": "/usr/local/bin/ccache /builds/slave/m-beta-m64-0000000000000000000/build/src/clang/bin/clang++ -std=gnu++11", "host": "x86_64-apple-darwin11.2.0", "target": "x86_64-apple-darwin11.2.0", "number": 1}, "last_modified": 1520960552304}}}

exception calling callback for <Future at 0x7f671c0d4e48 state=finished returned list>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 414, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 620, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by peterbe** [comment]
From what I can understand, this happens when you run `latest-inventory-to-kinto` and any exception happens. The `RuntimeError: Event loop is closed` isn't particularly important. You have to scroll up to see the actual interesting exception. 

I'm going to close this because this traceback paste isn't particular actionable.
